// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/url.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UrlClient is the client API for Url service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrlClient interface {
	GetFullURL(ctx context.Context, in *GetFullURLRequest, opts ...grpc.CallOption) (*GetFullURLResponse, error)
	CreateShotrUrl(ctx context.Context, in *CreateShotrUrlRequest, opts ...grpc.CallOption) (*CreateShotrUrlResponse, error)
}

type urlClient struct {
	cc grpc.ClientConnInterface
}

func NewUrlClient(cc grpc.ClientConnInterface) UrlClient {
	return &urlClient{cc}
}

func (c *urlClient) GetFullURL(ctx context.Context, in *GetFullURLRequest, opts ...grpc.CallOption) (*GetFullURLResponse, error) {
	out := new(GetFullURLResponse)
	err := c.cc.Invoke(ctx, "/proto.Url/GetFullURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlClient) CreateShotrUrl(ctx context.Context, in *CreateShotrUrlRequest, opts ...grpc.CallOption) (*CreateShotrUrlResponse, error) {
	out := new(CreateShotrUrlResponse)
	err := c.cc.Invoke(ctx, "/proto.Url/CreateShotrUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlServer is the server API for Url service.
// All implementations should embed UnimplementedUrlServer
// for forward compatibility
type UrlServer interface {
	GetFullURL(context.Context, *GetFullURLRequest) (*GetFullURLResponse, error)
	CreateShotrUrl(context.Context, *CreateShotrUrlRequest) (*CreateShotrUrlResponse, error)
}

// UnimplementedUrlServer should be embedded to have forward compatible implementations.
type UnimplementedUrlServer struct {
}

func (UnimplementedUrlServer) GetFullURL(context.Context, *GetFullURLRequest) (*GetFullURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullURL not implemented")
}
func (UnimplementedUrlServer) CreateShotrUrl(context.Context, *CreateShotrUrlRequest) (*CreateShotrUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShotrUrl not implemented")
}

// UnsafeUrlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrlServer will
// result in compilation errors.
type UnsafeUrlServer interface {
	mustEmbedUnimplementedUrlServer()
}

func RegisterUrlServer(s grpc.ServiceRegistrar, srv UrlServer) {
	s.RegisterService(&Url_ServiceDesc, srv)
}

func _Url_GetFullURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFullURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlServer).GetFullURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Url/GetFullURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlServer).GetFullURL(ctx, req.(*GetFullURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Url_CreateShotrUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShotrUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlServer).CreateShotrUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Url/CreateShotrUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlServer).CreateShotrUrl(ctx, req.(*CreateShotrUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Url_ServiceDesc is the grpc.ServiceDesc for Url service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Url_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Url",
	HandlerType: (*UrlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFullURL",
			Handler:    _Url_GetFullURL_Handler,
		},
		{
			MethodName: "CreateShotrUrl",
			Handler:    _Url_CreateShotrUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/url.proto",
}
